steps:
  # Build the API server container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nba-api-server', './server']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nba-api-server']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nba-api-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nba-api-server'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - '/GEMINI_API_KEY=GEMINI_API_KEY:latest,/MONGO_URI=MONGO_URI:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'MCP_SERVER_URL=${_MCP_SERVER_URL}'

images:
  - 'gcr.io/$PROJECT_ID/nba-api-server'

substitutions:
  _MCP_SERVER_URL: ''  # This will be updated after MCP deployment 
