steps:
  # Build the client container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nba-client', './client']

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nba-client']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nba-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nba-client'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '5'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=${_API_SERVER_URL}'

images:
  - 'gcr.io/$PROJECT_ID/nba-client'

substitutions:
  _API_SERVER_URL: ''  # This will be updated after API deployment 
