services:
  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nba-agent-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - nba-net

  # AI Agent API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nba-agent-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MCP_SERVER_URL=http://mcp:8765
      - MONGO_URI=${MONGO_URI}
    depends_on:
      mcp:
        condition: service_healthy
    networks:
      - nba-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB MCP Data Server
  mcp:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: nba-mcp-server
    restart: unless-stopped
    ports:
      - "8765:8765"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8765
    networks:
      - nba-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nba-net:
    driver: bridge 